### ISSUE TITLE
Error from Docker with DriverKit when building for vanilla target (kernel version 5.10.x)

### ISSUE THREAD

**Issue by VariableExp0rt** [falcosecurity/driverkit#102]
Hey Falco Maintainers :) Thank you for this project!

**Describe the bug**

When building via DriverKit for a vanilla target, I am receiving the following error;

`✗ driverkit docker -c vanilla1.yaml --timeout 300
INFO using config file                             file=vanilla1.yaml
INFO driver building, it will take a few seconds   processor=docker
FATA exiting                                       error="Error: No such container:path: d43afc2dd325103bea60afd96d3a447c61b19b4517392d742783b8c8aeed1642:/tmp/driver/falco.ko"`

**How to reproduce it**

When using the following command;

`driverkit docker -c vanilla1.yaml --timeout 300`

With the following configuration;

```yaml
kernelrelease: 5.10.38-flatcar
kernelversion: 1
target: vanilla
output:
  module: /tmp/falco-vanilla.ko
  probe: /tmp/falco-vanilla.o
driverversion: 0de226085cc4603c45ebb6883ca4cacae0bd25b2
kernelconfigdata: ...
```

**Expected behaviour**

The kernel module is built and dropped into `/tmp/falco-vanilla.ko`

**Environment**

- Falco version: `0.28.0`
- System info: `Built using macOS Big Sur 11.3.1`
- Kernel: `Darwin Kernel Version 20.4.0`
- Installation method: `go get github.com/falcosecurity/driverkit`

**Additional context**
If there is something I am missing around how to build the Falco kernel module using driverkit, I'd love to get more acquainted with the tool! I saw some other issues, namely [here](https://github.com/falcosecurity/driverkit/issues/21) and [here](https://github.com/falcosecurity/test-infra/pull/103#issuecomment-600138977) which leads me to believe that this would work (without the flatcar target explicitly). The falco-driver-loader docker approach works fine and and loads the kernel module after modifying the flatcar image using the following guide [here](https://kinvolk.io/docs/flatcar-container-linux/latest/reference/developer-guides/kernel-modules/), but I really need the artifact (falco-vanilla.ko) which I can fetch at boot in our environment.

Thanks! :)

**Comment by VariableExp0rt** [comment]
Additionally, I can successfully compile the kernel module for the same target in the other issue mentioned above;
```
✗ driverkit docker -c vanilla.yaml --timeout 300
INFO using config file                             file=vanilla.yaml
INFO driver building, it will take a few seconds   processor=docker
INFO kernel module available                       path=/tmp/falco-vanilla.ko
INFO eBPF probe available                          path=/tmp/falco-vanilla.o
```
Using

```
kernelrelease: 4.19.106-flatcar
kernelversion: 1
target: vanilla
output:
  module: /tmp/falco-vanilla.ko
  probe: /tmp/falco-vanilla.o
driverversion: 0de226085cc4603c45ebb6883ca4cacae0bd25b2
kernelconfigdata: ...
```

I guess the kernels 5.x.x kernels are not yet supported?
