### ISSUE TITLE
Driverkit fails to build Ubuntu releases

### ISSUE THREAD

**Issue by distortedsignal** [falcosecurity/driverkit#126]
**Describe the bug**

Current HEAD doesn't build successfully for supported Ubuntu releases.

AS A new developer to driverkit,
I WANT to build the Ubuntu drivers to make sure that I'm doing things right
WHEN I TRY... the driverkit fails with... lots of errors.

**How to reproduce it**

1. Clone the driverkit project into a new directory.
    * `mkdir repros && cd repros && git clone https://github.com/falcosecurity/driverkit.git && cd driverkit`
1. Build driverkit using `make build`
    * `make build`
    *  Output attached below in \[1\]
1. EXPECT: the `driverkit` binary to be built and stored at `_output/bin/driverkit`
    * This step completed successfully
1. Attempt to use the new driverkit binary to build drivers for Ubuntu distros listed in the driverkit README
    1. Make files that specify how drivers/eBPFs should be built.
        * These files are listed in \[2\]
    1. Call the newly created driverkit binary with these files as the config file.
        * I initially tried this with `debug` logging, and... y'all love your debug logging, huh? I got like 30k lines worth of logs off one build.
        * `_output/bin/driverkit docker -c /home/tom/Documents/src/falco/ubuntu-generic.yaml &> ./ubuntu-generic.log`
        * `_output/bin/driverkit docker -c /home/tom/Documents/src/falco/ubuntu-aws.yaml &> ./ubuntu-aws.log`
    1. EXPECT: the drivers to be created and placed in the specified file/directory.
        * And... this is where we fail. No compiled files are created.
        * Log files are collected in \[3\]

<details>
<summary>[1] Make build output</summary>

```
rm -f -R dist
rm -f -R _output
CGO_ENABLED=1 go build -v -ldflags '-X github.com/falcosecurity/driverkit/pkg/version.buildTime=1645123753 -X github.com/falcosecurity/driverkit/pkg/version.gitCommit=10b957d -X github.com/falcosecurity/driverkit/pkg/version.gitTag=v0.5.0 -X github.com/falcosecurity/driverkit/pkg/version.commitsFromGitTag=3 -X github.com/falcosecurity/driverkit/pkg/driverbuilder.builderBaseImage=docker.io/falcosecurity/driverkit-builder:10b957d' -tags 'sqlite_omit_load_extension linux' -o _output/bin/driverkit .
# github.com/mattn/go-sqlite3
sqlite3-binding.c: In function ‘sqlite3SelectNew’:
sqlite3-binding.c:128049:10: warning: function may return address of local variable [-Wreturn-local-addr]
128049 |   return pNew;
       |          ^~~~
sqlite3-binding.c:128009:10: note: declared here
128009 |   Select standin;
       |          ^~~~~~~
```

</details>

<details>
<summary>[2] Files passed to driverkit</summary>

<details>
<summary>Ubuntu Generic File</summary>

```yaml
kernelrelease: 4.15.0-72-generic
kernelversion: 81
target: ubuntu-generic
output:
  module: /home/tom/Documents/src/falco/driver-out/falco-ubuntu-generic.ko
  probe: /home/tom/Documents/src/falco/driver-out/falco-ubuntu-generic.o
driverversion: master
```

</details>

<details>
<summary>AWS Ubuntu File</summary>

```yaml
kernelrelease: 4.15.0-1057-aws
kernelversion: 59
target: ubuntu-aws
output:
  module: /home/tom/Documents/src/falco/driver-out/falco-ubuntu-aws.ko
  probe: /home/tom/Documents/src/falco/driver-out/falco-ubuntu-aws.o
driverversion: master
```

</details>

</details>

<details>
<summary>[3] Build output log files</summary>

<details>
<summary>Ubuntu Generic Log file</summary>

```
INFO using config file                             file=/home/tom/Documents/src/falco/ubuntu-generic.yaml
INFO driver building, it will take a few seconds   processor=docker
FATA exiting                                       error="Error: No such container:path: e1135c7a0565ed73c3ecfdaeaf1fb0f32ccb68966b96f354cd3ecd3f6f0950a8:/tmp/driver/module.ko"
```

</details>

<details>
<summary>AWS Ubuntu Log file</summary>

```
INFO using config file                             file=/home/tom/Documents/src/falco/ubuntu-aws.yaml
INFO driver building, it will take a few seconds   processor=docker
FATA exiting                                       error="Error: No such container:path: befba3c012fe1c7c83f99f14976782f0783588b4f437b923343a547569c44db0:/tmp/driver/module.ko"
```

</details>

</details>

**Environment**

- Falco version: N/A

- System info: N/A

- Cloud provider or hardware configuration: N/A
- OS:
```
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux
```

- Kernel:
```
Linux tom-virtualbox 5.16.7-1-MANJARO #1 SMP PREEMPT Sun Feb 6 12:22:29 UTC 2022 x86_64 GNU/Linux
```

- Installation method:
Uh... from an ISO? Not sure how this is relevant.

**Additional context**
