### ISSUE TITLE
Unknown argument error for building centos eBPF module

### ISSUE THREAD

**Issue by derekhjray** [falcosecurity/driverkit#145]
**Describe the bug**
Build eBPF module triggers  "**unknown argument: '-fmacro-prefix-map=./='**" error

**How to reproduce it**

Build centos7 community version 5.14.11:
```
kernelversion: 1
kernelrelease: 5.14.11-1.el7.elrepo.x86_64
target: centos
output:
  module: output/319368f1ad778691164d33d59945e00c5752cd27/falco_centos_5.14.11-1.el7.elrepo.x86_64.ko
  probe: output/319368f1ad778691164d33d59945e00c5752cd27/falco_centos_5.14.11-1.el7.elrepo.x86_64.o
```
Kernel devel repository url: https://mirrors.aliyun.com/elrepo/kernel

**Expected behaviour**
Build with no error

**Screenshots**
![1652842404(1)](https://user-images.githubusercontent.com/80803555/168947518-7586563e-db69-4883-8db9-97d24fc8740f.png)

**Environment**

- Falco version:

```
Falco version: 0.31.1
Driver version: 319368f1ad778691164d33d59945e00c5752cd27
```
- System info:

```
{
  "machine": "x86_64",
  "nodename": "ubunut-1",
  "release": "5.13.0-28-generic",
  "sysname": "Linux",
  "version": "#31~20.04.1-Ubuntu SMP Wed Jan 19 14:08:10 UTC 2022"
}
```

- Cloud provider or hardware configuration:
- OS:

```
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

- Kernel:

`Linux anesec 5.13.0-28-generic #31~20.04.1-Ubuntu SMP Wed Jan 19 14:08:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- Installation method:

**Additional context**
