### ISSUE TITLE
Errors building Falco drivers for Linux kernels 5.10.x

### ISSUE THREAD

**Issue by leodido** [falcosecurity/driverkit#81]
**Describe the bug**

The driverkit internal scripts do not work for Linux kernels 5.10.x.

**How to reproduce it**

Given this configuration file (named "d510.yaml"):

```yaml
kernelversion: 1
kernelrelease: 5.10.0-1-amd64
target: debian
output:
  module: output/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/falco_debian_5.10.0-1-amd64_1.ko
  probe: output/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/falco_debian_5.10.0-1-amd64_1.o
```

Execute:

```console
make build
./_output/bin/driverkit docker --loglevel debug -c d510.yaml
```

**Expected behavior**

To build Falco drivers for the specified Linux Kernel 5.10.

**Screenshots**

```console
DEBU I+ make CC=/usr/bin/gcc-8 KERNELDIR=/usr/src/linux-headers-5.10.0-1-amd64 
DEBU Dmake -C /usr/src/linux-headers-5.10.0-1-amd64 M=/tmp/driver modules 
DEBU make[1]: Entering directory '/usr/src/linux-headers-5.10.0-1-amd64' 
DEBU make[1]: Leaving directory '/usr/src/linux-headers-5.10.0-1-amd64' 
DEBU Makefile:1: /usr/src/linux-headers-5.10.0-1-common/Makefile: No such file or directory 
DEBU make[1]: *** No rule to make target '/usr/src/linux-headers-5.10.0-1-common/Makefile'.  Stop. 
DEBU $make: *** [Makefile:7: all] Error 2
```
